2016-04-07 01:58:08.561 [error] <0.305.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.310.0> exit with reason normal in context child_terminated
2016-04-07 01:58:08.592 [info] <0.7.0> Application lager started on node 'IEX-67b1@Luca-Cortis-MacBook-Pro'
2016-04-07 01:58:08.592 [info] <0.7.0> Application hpack started on node 'IEX-67b1@Luca-Cortis-MacBook-Pro'
2016-04-07 01:58:08.592 [info] <0.7.0> Application chatterbox started on node 'IEX-67b1@Luca-Cortis-MacBook-Pro'
2016-04-07 01:58:08.597 [info] <0.7.0> Application cartel started on node 'IEX-67b1@Luca-Cortis-MacBook-Pro'
2016-04-07 01:58:33.740 [error] <0.365.0> gen_server <0.365.0> terminated with reason: no match of right hand value {error,{{badmatch,{error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19
2016-04-07 01:58:33.741 [error] <0.365.0> CRASH REPORT Process <0.365.0> with 1 neighbours exited with reason: no match of right hand value {error,{{badmatch,{error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19 in gen_server:terminate/7 line 826
2016-04-07 01:58:33.741 [error] <0.360.0> Supervisor {<0.360.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.365.0> exit with reason no match of right hand value {error,{{badmatch,{error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19 in context child_terminated
2016-04-07 02:00:15.559 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.176.0> exit with reason normal in context child_terminated
2016-04-07 02:00:15.588 [info] <0.7.0> Application lager started on node 'IEX-b42f@Luca-Cortis-MacBook-Pro'
2016-04-07 02:00:15.588 [info] <0.7.0> Application hpack started on node 'IEX-b42f@Luca-Cortis-MacBook-Pro'
2016-04-07 02:00:15.588 [info] <0.7.0> Application chatterbox started on node 'IEX-b42f@Luca-Cortis-MacBook-Pro'
2016-04-07 02:00:15.599 [info] <0.7.0> Application cartel started on node 'IEX-b42f@Luca-Cortis-MacBook-Pro'
2016-04-07 02:00:18.176 [error] <0.265.0> CRASH REPORT Process <0.265.0> with 1 neighbours exited with reason: no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:00:18.176 [error] <0.226.0> Supervisor {<0.226.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.231.0> exit with reason no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in context child_terminated
2016-04-07 02:01:16.969 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.176.0> exit with reason normal in context child_terminated
2016-04-07 02:01:16.997 [info] <0.7.0> Application lager started on node 'IEX-d8ca@Luca-Cortis-MacBook-Pro'
2016-04-07 02:01:16.997 [info] <0.7.0> Application hpack started on node 'IEX-d8ca@Luca-Cortis-MacBook-Pro'
2016-04-07 02:01:16.997 [info] <0.7.0> Application chatterbox started on node 'IEX-d8ca@Luca-Cortis-MacBook-Pro'
2016-04-07 02:01:17.013 [info] <0.7.0> Application cartel started on node 'IEX-d8ca@Luca-Cortis-MacBook-Pro'
2016-04-07 02:01:28.677 [error] <0.265.0> CRASH REPORT Process <0.265.0> with 1 neighbours exited with reason: no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:01:28.677 [error] <0.226.0> Supervisor {<0.226.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.231.0> exit with reason no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in context child_terminated
2016-04-07 02:02:07.991 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 1 neighbours exited with reason: no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:02:07.991 [error] <0.226.0> Supervisor {<0.226.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.267.0> exit with reason no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in context child_terminated
2016-04-07 02:06:19.239 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.150.0> exit with reason normal in context child_terminated
2016-04-07 02:06:19.263 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:06:19.263 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:06:19.264 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:06:19.276 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:06:42.640 [error] <0.239.0> CRASH REPORT Process <0.239.0> with 1 neighbours exited with reason: no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:06:42.640 [error] <0.200.0> Supervisor {<0.200.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.205.0> exit with reason no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in context child_terminated
2016-04-07 02:10:06.958 [error] <0.245.0> CRASH REPORT Process <0.245.0> with 1 neighbours exited with reason: no match of right hand value {error,{options,{socket_options,[{mode,binary},{packet,raw},{active,once}]}}} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:10:37.581 [error] <0.252.0> CRASH REPORT Process <0.252.0> with 1 neighbours exited with reason: no function clause matching proplists:delete(binary, nil) line 367 in gen_fsm:init_it/6 line 396
2016-04-07 02:11:52.483 [error] <0.256.0> CRASH REPORT Process <0.256.0> with 1 neighbours exited with reason: no function clause matching proplists:delete(binary, nil) line 367 in gen_fsm:init_it/6 line 396
2016-04-07 02:12:25.522 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:12:25.552 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:12:25.552 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:12:25.552 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:12:25.563 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:16:35.308 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason killed in context child_terminated
2016-04-07 02:16:46.306 [error] <0.284.0> gen_server <0.284.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.284.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2016-04-07 02:16:46.307 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 2 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.284.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in gen_server:terminate/7 line 826
2016-04-07 02:16:46.307 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.284.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.284.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2016-04-07 02:18:59.292 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:18:59.319 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:18:59.319 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:18:59.319 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:18:59.331 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:19:03.559 [error] <0.218.0> gen_server <0.218.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.252.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2016-04-07 02:19:03.559 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 2 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.252.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in gen_server:terminate/7 line 826
2016-04-07 02:19:03.559 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => nil,protocol => 'Elixir.String.Chars',value => <0.252.0>} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2016-04-07 02:19:25.670 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:19:25.699 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:19:25.700 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:19:25.700 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:19:25.710 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:19:28.749 [error] <0.252.0> gen_fsm <0.252.0> in state connected terminated with reason: bad argument in call to erlang:size("api.development.push.apple.com") in hpack:encode_literal/1 line 224
2016-04-07 02:19:28.749 [error] <0.252.0> CRASH REPORT Process <0.252.0> with 3 neighbours exited with reason: bad argument in call to erlang:size("api.development.push.apple.com") in hpack:encode_literal/1 line 224
2016-04-07 02:19:28.750 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason bad argument in call to erlang:size("api.development.push.apple.com") in hpack:encode_literal/1 line 224 in context child_terminated
2016-04-07 02:20:24.515 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:20:24.542 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:20:24.542 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:20:24.543 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:20:24.554 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:20:27.178 [error] <0.218.0> gen_server <0.218.0> terminated with reason: bad argument in 'Elixir.Cartel.Pusher.Apns2':headers/1 line 33
2016-04-07 02:20:27.178 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 2 neighbours exited with reason: bad argument in 'Elixir.Cartel.Pusher.Apns2':headers/1 line 33
2016-04-07 02:20:27.178 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason bad argument in 'Elixir.Cartel.Pusher.Apns2':headers/1 line 33 in context child_terminated
2016-04-07 02:22:21.123 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:22:21.151 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:22:21.151 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:22:21.151 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:22:21.161 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:22:23.806 [error] <0.252.0> gen_fsm <0.252.0> in state connected terminated with reason: bad argument in call to erlang:byte_size({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) in http2_frame_data:to_frames/3 line 40
2016-04-07 02:22:23.806 [error] <0.252.0> CRASH REPORT Process <0.252.0> with 3 neighbours exited with reason: bad argument in call to erlang:byte_size({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) in http2_frame_data:to_frames/3 line 40
2016-04-07 02:22:23.806 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason bad argument in call to erlang:byte_size({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) in http2_frame_data:to_frames/3 line 40 in context child_terminated
2016-04-07 02:24:58.147 [error] <0.270.0> CRASH REPORT Process <0.270.0> with 1 neighbours exited with reason: no match of right hand value {error,closed} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:24:58.147 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.260.0> exit with reason no match of right hand value {error,closed} in http2_connection:init/1 line 138 in context child_terminated
2016-04-07 02:25:16.977 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:25:17.005 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:25:17.005 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:25:17.005 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:25:17.017 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:25:19.783 [error] <0.218.0> gen_server <0.218.0> terminated with reason: no function clause matching 'Elixir.String':to_char_list({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) line 1633
2016-04-07 02:25:19.783 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 2 neighbours exited with reason: no function clause matching 'Elixir.String':to_char_list({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) line 1633 in gen_server:terminate/7 line 826
2016-04-07 02:25:19.783 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching 'Elixir.String':to_char_list({ok,<<"{\"aps\":{\"alert\":\"ciao\"}}">>}) line 1633 in context child_terminated
2016-04-07 02:26:42.281 [error] <0.163.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.168.0> exit with reason normal in context child_terminated
2016-04-07 02:26:42.307 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:26:42.308 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:26:42.308 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:26:42.319 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:26:45.102 [error] <0.264.0> gen_fsm <0.264.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.257.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6758>,tls_connection,undefined},<0.261.0>}},...}) line 480
2016-04-07 02:26:45.102 [error] <0.264.0> CRASH REPORT Process <0.264.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.257.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6758>,tls_connection,undefined},<0.261.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-07 02:26:45.103 [error] <0.218.0> Supervisor {<0.218.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.223.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.257.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6758>,tls_connection,undefined},<0.261.0>}},...}) line 480 in context child_terminated
2016-04-07 02:28:30.516 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 1 neighbours exited with reason: no match of right hand value {error,closed} in http2_connection:init/1 line 138 in gen_fsm:init_it/6 line 396
2016-04-07 02:28:30.523 [error] <0.265.0> gen_server <0.265.0> terminated with reason: no match of right hand value {error,{{badmatch,{error,closed}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19
2016-04-07 02:28:30.523 [error] <0.265.0> CRASH REPORT Process <0.265.0> with 0 neighbours exited with reason: no match of right hand value {error,{{badmatch,{error,closed}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19 in gen_server:terminate/7 line 826
2016-04-07 02:28:30.523 [error] <0.218.0> Supervisor {<0.218.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.265.0> exit with reason no match of right hand value {error,{{badmatch,{error,closed}},[{http2_connection,init,1,[{file,"src/http2_connection.erl"},{line,138}]},{gen_fsm,init_it,6,[{file,"gen_fsm.erl"},{line,378}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in 'Elixir.Cartel.Pusher.Apns2':connect/1 line 19 in context child_terminated
2016-04-07 02:29:52.362 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.150.0> exit with reason normal in context child_terminated
2016-04-07 02:29:52.387 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:29:52.387 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:29:52.387 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:29:52.400 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:30:00.467 [error] <0.246.0> gen_fsm <0.246.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.239.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6419>,tls_connection,undefined},<0.243.0>}},...}) line 480
2016-04-07 02:30:00.467 [error] <0.246.0> CRASH REPORT Process <0.246.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.239.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6419>,tls_connection,undefined},<0.243.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-07 02:30:00.467 [error] <0.200.0> Supervisor {<0.200.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.205.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.239.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6419>,tls_connection,undefined},<0.243.0>}},...}) line 480 in context child_terminated
2016-04-07 02:38:44.023 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-07 02:38:44.049 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-07 02:38:44.049 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-07 02:38:44.049 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-07 02:38:44.061 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-07 02:38:46.799 [error] <0.259.0> gen_fsm <0.259.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480
2016-04-07 02:38:46.799 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-07 02:38:46.799 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in context child_terminated
2016-04-09 00:46:04.225 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.150.0> exit with reason normal in context child_terminated
2016-04-09 00:46:04.250 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 00:46:04.250 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 00:46:04.250 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 00:46:04.267 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 00:49:18.261 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-09 00:49:18.289 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 00:49:18.290 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 00:49:18.290 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 00:49:18.300 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 00:49:21.502 [error] <0.259.0> gen_fsm <0.259.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480
2016-04-09 00:49:21.502 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-09 00:49:21.502 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in context child_terminated
2016-04-09 00:51:42.098 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-09 00:51:42.126 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 00:51:42.126 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 00:51:42.126 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 00:51:42.137 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 00:51:53.492 [error] <0.260.0> gen_fsm <0.260.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.253.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6653>,tls_connection,undefined},<0.257.0>}},...}) line 480
2016-04-09 00:51:53.492 [error] <0.260.0> CRASH REPORT Process <0.260.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.253.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6653>,tls_connection,undefined},<0.257.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-09 00:51:53.493 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.253.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6653>,tls_connection,undefined},<0.257.0>}},...}) line 480 in context child_terminated
2016-04-09 00:57:39.455 [error] <0.308.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.313.0> exit with reason normal in context child_terminated
2016-04-09 00:57:39.485 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 00:57:39.485 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 00:57:39.486 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 00:57:39.489 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 00:57:50.056 [error] <0.409.0> gen_fsm <0.409.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.402.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.13518>,tls_connection,undefined},<0.406.0>}},...}) line 480
2016-04-09 00:57:50.056 [error] <0.409.0> CRASH REPORT Process <0.409.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.402.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.13518>,tls_connection,undefined},<0.406.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-09 00:57:50.056 [error] <0.363.0> Supervisor {<0.363.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.368.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.402.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.13518>,tls_connection,undefined},<0.406.0>}},...}) line 480 in context child_terminated
2016-04-09 01:02:13.091 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-09 01:02:13.121 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 01:02:13.121 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 01:02:13.121 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 01:02:13.134 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 01:02:21.156 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.150.0> exit with reason normal in context child_terminated
2016-04-09 01:02:21.184 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 01:02:21.184 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 01:02:21.184 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 01:02:21.199 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 01:02:32.162 [error] <0.205.0> gen_server <0.205.0> terminated with reason: no match of right hand value {ok,1} in 'Elixir.Cartel.Pusher.Apns2':handle_call/3 line 49
2016-04-09 01:02:32.162 [error] <0.205.0> CRASH REPORT Process <0.205.0> with 3 neighbours exited with reason: no match of right hand value {ok,1} in 'Elixir.Cartel.Pusher.Apns2':handle_call/3 line 49 in gen_server:terminate/7 line 826
2016-04-09 01:02:32.162 [error] <0.200.0> Supervisor {<0.200.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.205.0> exit with reason no match of right hand value {ok,1} in 'Elixir.Cartel.Pusher.Apns2':handle_call/3 line 49 in context child_terminated
2016-04-09 01:05:58.749 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-09 01:05:58.778 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 01:05:58.779 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 01:05:58.779 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 01:05:58.789 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 01:06:03.017 [error] <0.259.0> gen_fsm <0.259.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480
2016-04-09 01:06:03.017 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-09 01:06:03.017 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in context child_terminated
2016-04-09 01:07:25.251 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-04-09 01:07:25.278 [info] <0.7.0> Application lager started on node nonode@nohost
2016-04-09 01:07:25.279 [info] <0.7.0> Application hpack started on node nonode@nohost
2016-04-09 01:07:25.279 [info] <0.7.0> Application chatterbox started on node nonode@nohost
2016-04-09 01:07:25.290 [info] <0.7.0> Application cartel started on node nonode@nohost
2016-04-09 01:07:26.586 [error] <0.259.0> gen_fsm <0.259.0> in state half_closed_local terminated with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480
2016-04-09 01:07:26.587 [error] <0.259.0> CRASH REPORT Process <0.259.0> with 3 neighbours exited with reason: no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in gen_fsm:terminate/7 line 626
2016-04-09 01:07:26.587 [error] <0.213.0> Supervisor {<0.213.0>,poolboy_sup} had child undefined started with {'Elixir.Cartel.Pusher.Apns2',start_link,undefined} at <0.218.0> exit with reason no function clause matching http2_stream:half_closed_local(recv_es, {stream_state,1,<0.252.0>,{ssl,{sslsocket,{gen_tcp,#Port<0.6581>,tls_connection,undefined},<0.256.0>}},...}) line 480 in context child_terminated
